// Package demo provides a self-contained, deliberately paced qcode session.
// It never contacts a model or executes a real tool.
package demo

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"qcode/internal/llm"
)

const (
	// Model is a display-only model name used by the demo session.
	Model        = "scripted-demo"
	defaultDelay = 1500 * time.Millisecond
)

// Session contains both mocked boundaries needed by the normal agent loop.
type Session struct {
	Provider *Provider
	Tools    *Toolset
}

// New creates a demo session from the production tool schemas. This makes the
// scenario automatically exercise newly registered tools without executing
// their production handlers.
func New(schemas []llm.Tool) *Session {
	return newSession(schemas, defaultDelay)
}

func newSession(schemas []llm.Tool, delay time.Duration) *Session {
	copied := append([]llm.Tool(nil), schemas...)
	return &Session{
		Provider: &Provider{delay: delay},
		Tools:    &Toolset{schemas: copied, delay: delay},
	}
}

// Provider returns one scripted batch containing every advertised tool, then
// a final response after their mocked results have been added to the history.
type Provider struct {
	delay time.Duration
}

func (p *Provider) Name() string { return "demo" }

func (p *Provider) Complete(ctx context.Context, request llm.Request, onText llm.StreamCallback) (llm.Response, error) {
	if err := wait(ctx, p.delay); err != nil {
		return llm.Response{}, err
	}
	if toolResultsSinceLastUser(request.Messages) == 0 && len(request.Tools) > 0 {
		if onText != nil {
			onText(llm.StreamEvent{Kind: llm.StreamThinking, Text: "Demo mode: planning a safe, mocked tour of every available tool.\n"})
		}
		calls := make([]llm.ToolCall, 0, len(request.Tools))
		for index, schema := range request.Tools {
			calls = append(calls, llm.ToolCall{
				ID:        fmt.Sprintf("demo_%d_%s", index+1, schema.Name),
				Name:      schema.Name,
				Arguments: demoArguments(schema.Name),
			})
		}
		return llm.Response{Message: llm.Message{
			Role:      "assistant",
			Thinking:  "Demo mode is exercising every available tool with mocked arguments.",
			ToolCalls: calls,
		}}, nil
	}

	message := fmt.Sprintf("Demo complete. The mocked LLM connection succeeded and all %d available tools ran without reading, changing, or executing anything in your workspace.", len(request.Tools))
	if onText != nil {
		onText(llm.StreamEvent{Kind: llm.StreamOutput, Text: message})
	}
	return llm.Response{Message: llm.Message{Role: "assistant", Content: message}}, nil
}

func toolResultsSinceLastUser(messages []llm.Message) int {
	count := 0
	for index := len(messages) - 1; index >= 0; index-- {
		switch messages[index].Role {
		case "user":
			return count
		case "tool":
			count++
		}
	}
	return count
}

// Toolset exposes real schemas and returns realistic but side-effect-free
// results. The delay is context-aware so Ctrl+C can cancel every tool phase.
type Toolset struct {
	schemas []llm.Tool
	delay   time.Duration
}

func (t *Toolset) Schemas() []llm.Tool {
	return append([]llm.Tool(nil), t.schemas...)
}

func (t *Toolset) ExecuteDetailed(ctx context.Context, call llm.ToolCall) (llm.ToolResult, error) {
	if err := wait(ctx, t.delay); err != nil {
		return llm.ToolResult{}, err
	}
	return llm.ToolResult{Output: demoOutput(call)}, nil
}

func wait(ctx context.Context, delay time.Duration) error {
	timer := time.NewTimer(delay)
	defer timer.Stop()
	select {
	case <-ctx.Done():
		return ctx.Err()
	case <-timer.C:
		return nil
	}
}

func demoArguments(name string) json.RawMessage {
	values := map[string]string{
		"read":   `{"path":"README.md","offset":1,"limit":20}`,
		"write":  `{"path":"demo/example.txt","content":"This write is mocked; no file will be created.\n"}`,
		"edit":   `{"path":"demo/example.txt","old_text":"mocked","new_text":"simulated"}`,
		"list":   `{"path":"."}`,
		"search": `{"pattern":"TODO|FIXME","path":".","max_results":20}`,
		"shell":  `{"command":"go test ./...","timeout_ms":120000}`,
	}
	if value, ok := values[name]; ok {
		return json.RawMessage(value)
	}
	return json.RawMessage(`{}`)
}

func demoOutput(call llm.ToolCall) string {
	switch call.Name {
	case "read":
		return "     1\t# qcode demo\n     2\tThis content is generated by the mocked read tool."
	case "write":
		return "wrote 48 bytes to demo/example.txt (mocked; workspace unchanged)"
	case "edit":
		return "edited demo/example.txt (mocked; workspace unchanged)"
	case "list":
		return "README.md\ncmd/\ninternal/\n(mocked listing)"
	case "search":
		return "internal/demo/demo.go:1:// Mocked search result"
	case "shell":
		return "ok\tqcode/internal/demo\t0.001s\n(mocked command; nothing was executed)"
	default:
		return fmt.Sprintf("%s completed with mocked arguments %s", call.Name, strings.TrimSpace(string(call.Arguments)))
	}
}
