package remote

const indexHTML = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>qcode remote</title><style>
:root{color-scheme:dark;--bg:#07090d;--panel:#0d1117;--line:#253041;--muted:#8190a5;--text:#d8e0ea;--cyan:#43d9e8;--green:#54d17a;--yellow:#e8bf55}
*{box-sizing:border-box}html,body{height:100%;margin:0;background:var(--bg);color:var(--text);font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}
body{display:grid;grid-template-rows:auto 1fr auto;overflow:hidden}.top{background:var(--panel);border-bottom:1px solid var(--line);padding:.55rem .8rem;display:flex;gap:.45rem;align-items:center;overflow-x:auto}
.brand{color:var(--cyan);font-weight:800;margin-right:.5rem}.tab{border:1px solid transparent;background:transparent;color:var(--muted);border-radius:.3rem;padding:.35rem .6rem;white-space:nowrap;cursor:pointer}.tab.active{border-color:var(--cyan);color:var(--text)}.tab.running:after{content:' ●';color:var(--green)}
main{overflow:auto;padding:1rem;scrollbar-color:var(--line) transparent}.transcript{margin:0;white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.48;font:inherit}.empty{color:var(--muted)}
.bottom{background:var(--panel);border-top:1px solid var(--line);padding:.55rem .75rem}.status{font-size:.76rem;color:var(--muted);margin-bottom:.45rem;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.status .online{color:var(--green)}.interaction,.command-panel{display:none;border:1px solid var(--yellow);border-radius:.35rem;margin-bottom:.55rem;padding:.65rem}.interaction.open,.command-panel.open{display:block}.interaction-title,.command-title{color:var(--yellow);margin-bottom:.45rem}.command-help{color:var(--muted);font-size:.8rem;margin:.25rem 0 .5rem}.command-actions{display:flex;gap:.4rem;margin-top:.5rem}.command-actions .cancel{background:var(--line);color:var(--text);font-weight:400}.choices{display:flex;flex-wrap:wrap;gap:.4rem}.choices button{background:var(--line);color:var(--text);font-weight:400}.selector-list{display:grid;gap:.3rem;max-height:14rem;overflow:auto;margin:.5rem 0}.selector-list button{text-align:left;background:var(--line);color:var(--text);font-weight:400}.selector-empty{color:var(--muted);padding:.35rem 0}
form{display:flex;gap:.55rem}input{flex:1;min-width:0;background:#080b10;border:1px solid var(--line);border-radius:.35rem;color:var(--text);font:inherit;padding:.65rem .75rem;outline:none}input:focus{border-color:var(--cyan)}button{background:var(--cyan);border:0;border-radius:.35rem;color:#001014;font:inherit;font-weight:800;padding:.55rem .9rem;cursor:pointer}button:disabled{opacity:.5}.notice{color:var(--yellow)}
@media(max-width:600px){main{padding:.7rem}.brand{display:none}.top{padding:.4rem}.bottom{padding:.5rem}.tab{padding:.3rem .45rem}}
</style></head><body>
<header class="top"><span class="brand">qcode</span><nav id="tabs"></nav></header>
<main id="scroll"><pre id="transcript" class="transcript empty">Connecting…</pre></main>
<footer class="bottom"><div id="interaction" class="interaction"></div><div id="command" class="command-panel"></div><div id="status" class="status">Connecting to qcode…</div><form id="form"><input id="input" autocomplete="off" spellcheck="false" placeholder="Send a prompt or slash command"><button id="send">Send</button></form></footer>
<script>
(()=>{
const tabs=document.querySelector('#tabs'),out=document.querySelector('#transcript'),status=document.querySelector('#status'),interaction=document.querySelector('#interaction'),command=document.querySelector('#command'),form=document.querySelector('#form'),input=document.querySelector('#input'),send=document.querySelector('#send'),scroll=document.querySelector('#scroll');
let snapshot=null,active='',timer=0,closed=false;const cleared={};
const ansi16=['#000000','#800000','#008000','#808000','#000080','#800080','#008080','#c0c0c0','#808080','#ff0000','#00ff00','#ffff00','#0000ff','#ff00ff','#00ffff','#ffffff'];
function schedule(){clearTimeout(timer);timer=setTimeout(load,70)}
async function load(){if(closed)return;try{const r=await fetch('api/v1/snapshot',{cache:'no-store'});if(!r.ok)throw new Error(await r.text());snapshot=await r.json();render()}catch(e){status.innerHTML='<span class="notice">'+escapeHTML(String(e))+'</span>'}}
function escapeHTML(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ansi256(n){n=Math.max(0,Math.min(255,n));if(n<16)return ansi16[n];if(n<232){const v=n-16,c=x=>x?55+x*40:0;return '#'+[c(Math.floor(v/36)),c(Math.floor(v/6)%6),c(v%6)].map(x=>x.toString(16).padStart(2,'0')).join('')}return '#'+(8+(n-232)*10).toString(16).padStart(2,'0').repeat(3)}
function ansiHTML(value){let state={},text='',html='';const css=()=>[state.fg&&'color:'+state.fg,state.bg&&'background-color:'+state.bg,state.bold&&'font-weight:700',state.dim&&'opacity:.65',state.italic&&'font-style:italic',state.underline&&'text-decoration:underline',state.strike&&'text-decoration:line-through'].filter(Boolean).join(';');const flush=()=>{if(!text)return;const style=css(),safe=escapeHTML(text);html+=style?'<span style="'+style+'">'+safe+'</span>':safe;text=''};for(let i=0;i<value.length;){if(value[i]==='\x1b'&&value[i+1]==='['){const end=value.indexOf('m',i+2);if(end>=0){flush();const codes=value.slice(i+2,end).split(';').map(x=>x===''?0:Number(x)||0);for(let j=0;j<codes.length;j++){const c=codes[j];if(c===0)state={};else if(c===1)state.bold=true;else if(c===2)state.dim=true;else if(c===3)state.italic=true;else if(c===4)state.underline=true;else if(c===9)state.strike=true;else if(c===22){state.bold=false;state.dim=false}else if(c===23)state.italic=false;else if(c===24)state.underline=false;else if(c===29)state.strike=false;else if(c===39)delete state.fg;else if(c===49)delete state.bg;else if(c>=30&&c<=37)state.fg=ansi16[c-30];else if(c>=90&&c<=97)state.fg=ansi16[c-90+8];else if(c>=40&&c<=47)state.bg=ansi16[c-40];else if(c>=100&&c<=107)state.bg=ansi16[c-100+8];else if((c===38||c===48)&&codes[j+1]===5&&j+2<codes.length){state[c===38?'fg':'bg']=ansi256(codes[j+2]);j+=2}else if((c===38||c===48)&&codes[j+1]===2&&j+4<codes.length){state[c===38?'fg':'bg']='rgb('+codes[j+2]+','+codes[j+3]+','+codes[j+4]+')';j+=4}}i=end+1;continue}}text+=value[i++]};flush();return html}
function render(){if(!snapshot||!snapshot.presentation)return;const views=snapshot.presentation.views||[];if(!views.some(v=>v.id===active))active=snapshot.presentation.active||(views[0]&&views[0].id)||'';tabs.replaceChildren(...views.map(v=>{const b=document.createElement('button');b.className='tab '+(v.id===active?'active ':'')+(v.status==='running'?'running':'');b.textContent=v.name||v.id;b.onclick=()=>{active=v.id;render()};return b}));const v=views.find(v=>v.id===active);const nearBottom=scroll.scrollHeight-scroll.scrollTop-scroll.clientHeight<80;const lines=v?v.lines.slice(cleared[active]||0):[];out.innerHTML=lines.length?ansiHTML(lines.join('\n')):'No transcript yet.';out.className='transcript '+(lines.length?'':'empty');status.innerHTML=ansiHTML(snapshot.presentation.status_bar||'Connecting to qcode…');renderInteraction((snapshot.runtime.interactions||[]).find(x=>x.agent_id===active)||(snapshot.runtime.interactions||[])[0]);if(nearBottom)scroll.scrollTop=scroll.scrollHeight}
function choice(label,value,id){const b=document.createElement('button');b.textContent=label;b.onclick=()=>resolve(id,value);return b}
function renderInteraction(item){interaction.replaceChildren();interaction.className='interaction'+(item?' open':'');if(!item)return;let payload={};try{payload=typeof item.payload==='string'?JSON.parse(item.payload):item.payload||{}}catch(_){}const title=document.createElement('div');title.className='interaction-title';title.textContent=item.kind.replaceAll('_',' ');interaction.append(title);const choices=document.createElement('div');choices.className='choices';if(item.kind==='directory_approval'){title.textContent='Directory access: '+(payload.requested||'');choices.append(choice('Grant '+(payload.proposed||'requested path'),{selected:payload.proposed||payload.requested,approved:true},item.id),choice('Deny',{selected:'',approved:false},item.id))}else if(item.kind==='questions'){const questions=Array.isArray(payload)?payload:[];const fields=questions.map(q=>{const field=document.createElement('input'),options=q.Options||q.options||[];field.placeholder=(q.Text||q.text)+(options.length?' — '+options.join(' / '):'');field.autocomplete='off';interaction.append(field);return field});title.textContent='Questions';const answer=choice('Submit answers',null,item.id);answer.onclick=()=>resolve(item.id,fields.map(field=>field.value));choices.append(answer)}else if(item.kind==='learning_approval'){title.textContent='Apply the proposed global learning changes?';choices.append(choice('Apply',true,item.id),choice('Reject',false,item.id))}else{choices.append(choice('Start implementation','implement',item.id),choice('Stay in plan mode','stay',item.id))}interaction.append(choices)}
async function resolve(id,value){try{const r=await fetch('api/v1/interactions/'+encodeURIComponent(id)+'/resolve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({value})});if(!r.ok)throw new Error(await r.text());schedule()}catch(e){status.innerHTML='<span class="notice">'+escapeHTML(String(e))+'</span>'}}
function downloadExport(){const views=(snapshot.presentation.views||[]);let body='<h1>qcode session</h1>';for(const v of views)body+='<h2>'+escapeHTML(v.name||v.id)+'</h2><pre>'+escapeHTML(v.lines.join('\n').replace(/\x1b\[[0-?]*[ -\/]*[@-~]/g,''))+'</pre>';const blob=new Blob(['<!doctype html><meta charset="utf-8"><title>qcode session</title><style>body{background:#07090d;color:#d8e0ea;font-family:monospace;padding:2rem}pre{white-space:pre-wrap}</style>'+body],{type:'text/html'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='qcode-session.html';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function postLine(line){const r=await fetch('api/v1/actions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({line})});if(!r.ok)throw new Error(await r.text())}
async function submitLine(line){send.disabled=true;try{await postLine(line);input.value='';schedule()}catch(e){status.innerHTML='<span class="notice">'+escapeHTML(String(e))+'</span>'}finally{send.disabled=false;input.focus()}}
async function submitLines(lines){send.disabled=true;try{for(const line of lines)await postLine(line);input.value='';schedule()}catch(e){status.innerHTML='<span class="notice">'+escapeHTML(String(e))+'</span>'}finally{send.disabled=false;input.focus()}}
function closeCommand(){command.replaceChildren();command.className='command-panel';command.onkeydown=null;input.focus()}
function openCommand(title,help,placeholder,onSubmit,submitLabel='Apply'){input.value='';command.replaceChildren();command.className='command-panel open';const heading=document.createElement('div');heading.className='command-title';heading.textContent=title;const hint=document.createElement('div');hint.className='command-help';hint.textContent=help;const field=document.createElement('input');field.placeholder=placeholder;field.autocomplete='off';const actions=document.createElement('div');actions.className='command-actions';const apply=document.createElement('button');apply.textContent=submitLabel;const cancel=document.createElement('button');cancel.className='cancel';cancel.type='button';cancel.textContent='Cancel';const commit=()=>{const value=field.value.trim();if(!value)return;closeCommand();onSubmit(value)};apply.onclick=commit;cancel.onclick=closeCommand;field.onkeydown=e=>{if(e.key==='Escape'){e.preventDefault();closeCommand()}if(e.key==='Enter'){e.preventDefault();commit()}};actions.append(apply,cancel);command.append(heading,hint,field,actions);field.focus()}
function openCloseAgent(name){input.value='';command.replaceChildren();command.className='command-panel open';const heading=document.createElement('div');heading.className='command-title';heading.textContent='Close agent '+name+'?';const hint=document.createElement('div');hint.className='command-help';hint.textContent='This matches the TUI confirmation step.';const actions=document.createElement('div');actions.className='command-actions';const close=document.createElement('button');close.textContent='Close agent';close.onclick=()=>{closeCommand();submitLine('/agent close '+name+' --yes')};const cancel=document.createElement('button');cancel.className='cancel';cancel.type='button';cancel.textContent='Cancel';cancel.onclick=closeCommand;actions.append(close,cancel);command.append(heading,hint,actions);command.tabIndex=0;command.onkeydown=e=>{if(e.key==='Escape'){e.preventDefault();closeCommand()}};close.focus()}
async function catalog(){const r=await fetch('api/v1/catalog',{cache:'no-store'});if(!r.ok)throw new Error(await r.text());return r.json()}
function agents(){return snapshot&&snapshot.runtime&&snapshot.runtime.agents||snapshot&&snapshot.presentation&&snapshot.presentation.agents||[]}
function activeModel(){const item=agents().find(x=>x.id===active)||agents().find(x=>x.id===(snapshot&&snapshot.presentation&&snapshot.presentation.active));return item&&item.model||''}
function selectorItem(label,value){return{label:String(label||value),value:String(value)}}
function openList(title,help,items,selected,multi,apply){input.value='';command.replaceChildren();command.className='command-panel open';const heading=document.createElement('div');heading.className='command-title';heading.textContent=title;const hint=document.createElement('div');hint.className='command-help';hint.textContent=help;const filter=document.createElement('input');filter.placeholder='Type to filter';filter.autocomplete='off';const list=document.createElement('div');list.className='selector-list';const chosen=new Set(selected||[]);const draw=()=>{list.replaceChildren();const query=filter.value.trim().toLowerCase();const matches=items.filter(item=>item.label.toLowerCase().includes(query));if(!matches.length){const empty=document.createElement('div');empty.className='selector-empty';empty.textContent=query?'No matching entries.':'No entries available.';list.append(empty);return}for(const item of matches){const button=document.createElement('button');button.type='button';button.className='cancel';button.textContent=(chosen.has(item.value)?(multi?'[x] ':'> '):(multi?'[ ] ':'  '))+item.label;button.onclick=()=>{if(multi){if(chosen.has(item.value))chosen.delete(item.value);else chosen.add(item.value)}else{chosen.clear();chosen.add(item.value)}draw()};list.append(button)}};const actions=document.createElement('div');actions.className='command-actions';const ok=document.createElement('button');ok.textContent='Apply';const cancel=document.createElement('button');cancel.className='cancel';cancel.type='button';cancel.textContent='Cancel';const commit=()=>{const values=[...chosen];closeCommand();apply(values)};ok.onclick=commit;cancel.onclick=closeCommand;filter.oninput=draw;filter.onkeydown=e=>{if(e.key==='Escape'){e.preventDefault();closeCommand()}if(e.key==='Enter'){e.preventDefault();commit()}};actions.append(ok,cancel);command.append(heading,hint,filter,list,actions);draw();filter.focus()}
function chooseModel(data,kind,model){const thinking=data.thinking&&data.thinking[model];const prefix=kind==='agent-model'?'/agent new ':'/model ';if(!thinking||!Array.isArray(thinking.levels)||!thinking.levels.length){submitLine(prefix+model);return}const levels=thinking.levels.map(x=>selectorItem(x,x));const current=thinking.current?[thinking.current]:[];openList('Select thinking level','Choose a thinking level. Cancel leaves the model unchanged.',levels,current,false,v=>{if(!v[0])return;const line='/model '+model+' '+v[0];if(kind==='agent-model')submitLines([prefix+model,line]);else submitLine(line)})}
async function openCatalogSelector(kind){try{const data=await catalog();if(kind==='model'||kind==='agent-model'){const items=(data.models||[]).map(x=>selectorItem(x,x));const title=kind==='agent-model'?'New agent':'Select model';const help=kind==='agent-model'?'Choose a model for the new agent.':'Choose a model for the active agent.';openList(title,help,items,[activeModel()],false,v=>v[0]&&chooseModel(data,kind,v[0]));return}if(kind==='tool'){const items=(data.tools||[]).map(x=>selectorItem(x.name+(x.enabled?' · on':' · off'),x.name));const selected=(data.tools||[]).filter(x=>x.enabled).map(x=>x.name);openList('Select tools','Toggle tools, then apply the complete selection.',items,selected,true,v=>submitLines((data.tools||[]).map(x=>'/tool '+x.name+' '+(v.includes(x.name)?'on':'off'))));return}if(kind==='skill'){const items=(data.skills||[]).map(x=>selectorItem(x.name+(x.description?' — '+x.description:''),x.name));const selected=(data.skills||[]).filter(x=>x.selected).map(x=>x.name);openList('Select skills','Toggle workspace skills, then apply the complete selection.',items,selected,true,v=>submitLine('/skill '+(v.length?v.join(', '):'none')));return}if(kind==='resume'){const items=(data.sessions||[]).map(x=>{const when=x.saved||x.left||x.created;let date='';try{if(when)date=' · '+new Date(when).toLocaleString()}catch(_){}return selectorItem(x.preview+(x.agent_count?' · '+x.agent_count+' agents':'')+date,x.id)});openList('Resume session','Choose a saved session. The current session is excluded.',items,[],false,v=>v[0]&&submitLine('/resume '+v[0]));return}const items=agents().map(x=>selectorItem(x.id+' · '+(x.name||x.id)+' · '+(x.model||'unknown')+' · '+(x.status||'unknown'),x.id));openList('Switch agent','Choose an agent tab to make active in qcode.',items,[active],false,v=>{if(v[0]){active=v[0];render();submitLine('/agent switch '+v[0])}})}catch(e){status.innerHTML='<span class="notice">'+escapeHTML(String(e))+'</span>'}}
function handleCommand(line){if(line==='/model'){openCatalogSelector('model');return true}if(line==='/tool'){openCatalogSelector('tool');return true}if(line==='/skill'){openCatalogSelector('skill');return true}if(line==='/resume'){openCatalogSelector('resume');return true}if(line==='/agent'||line==='/agent new'){openCatalogSelector('agent-model');return true}if(line==='/agent list'||line==='/agent switch'){openCatalogSelector('agent');return true}const switching=line.match(/^\/agent switch\s+(\S+)$/);if(switching){const id=switching[1];if(!agents().some(x=>x.id===id)){status.innerHTML='<span class="notice">Unknown agent: '+escapeHTML(id)+'</span>';return true}active=id;render();submitLine('/agent switch '+id);return true}const closing=line.match(/^\/agent close\s+(\S+)$/);if(closing){openCloseAgent(closing[1]);return true}return false}
form.onsubmit=e=>{e.preventDefault();const line=input.value.trim();if(!line)return;if(line==='/exit'||line==='/quit'){closed=true;events.close();status.textContent='Disconnected';send.disabled=true;input.disabled=true;return}if(line==='/clear'){const v=(snapshot.presentation.views||[]).find(v=>v.id===active);cleared[active]=v?v.lines.length:0;input.value='';render();return}if(line.startsWith('/export')){downloadExport();input.value='';return}if(handleCommand(line))return;submitLine(line)};
const events=new EventSource('api/v1/events');events.addEventListener('refresh',schedule);events.addEventListener('runtime',schedule);events.onerror=()=>{status.innerHTML='<span class="notice">Reconnecting…</span>'};load();input.focus()
})();
</script></body></html>`
