package remote

const indexHTML = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>qcode remote</title><style>
:root{color-scheme:dark;--bg:#07090d;--panel:#0d1117;--line:#253041;--muted:#8190a5;--text:#d8e0ea;--cyan:#43d9e8;--green:#54d17a;--yellow:#e8bf55}
*{box-sizing:border-box}html,body{height:100%;margin:0;background:var(--bg);color:var(--text);font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}
body{display:grid;grid-template-rows:auto 1fr auto;overflow:hidden}.top{background:var(--panel);border-bottom:1px solid var(--line);padding:.55rem .8rem;display:flex;gap:.45rem;align-items:center;overflow-x:auto}
.brand{color:var(--cyan);font-weight:800;margin-right:.5rem}.tab{border:1px solid transparent;background:transparent;color:var(--muted);border-radius:.3rem;padding:.35rem .6rem;white-space:nowrap;cursor:pointer}.tab.active{border-color:var(--cyan);color:var(--text)}.tab.running:after{content:' ●';color:var(--green)}
main{overflow:auto;padding:1rem;scrollbar-color:var(--line) transparent}.transcript{margin:0;white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.48;font:inherit}.empty{color:var(--muted)}
.bottom{background:var(--panel);border-top:1px solid var(--line);padding:.55rem .75rem}.status{font-size:.76rem;color:var(--muted);margin-bottom:.45rem;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.status .online{color:var(--green)}.interaction{display:none;border:1px solid var(--yellow);border-radius:.35rem;margin-bottom:.55rem;padding:.65rem}.interaction.open{display:block}.interaction-title{color:var(--yellow);margin-bottom:.45rem}.choices{display:flex;flex-wrap:wrap;gap:.4rem}.choices button{background:var(--line);color:var(--text);font-weight:400}
form{display:flex;gap:.55rem}input{flex:1;min-width:0;background:#080b10;border:1px solid var(--line);border-radius:.35rem;color:var(--text);font:inherit;padding:.65rem .75rem;outline:none}input:focus{border-color:var(--cyan)}button{background:var(--cyan);border:0;border-radius:.35rem;color:#001014;font:inherit;font-weight:800;padding:.55rem .9rem;cursor:pointer}button:disabled{opacity:.5}.notice{color:var(--yellow)}
@media(max-width:600px){main{padding:.7rem}.brand{display:none}.top{padding:.4rem}.bottom{padding:.5rem}.tab{padding:.3rem .45rem}}
</style></head><body>
<header class="top"><span class="brand">qcode</span><nav id="tabs"></nav></header>
<main id="scroll"><pre id="transcript" class="transcript empty">Connecting…</pre></main>
<footer class="bottom"><div id="interaction" class="interaction"></div><div id="status" class="status">Connecting to qcode…</div><form id="form"><input id="input" autocomplete="off" spellcheck="false" placeholder="Send a prompt or slash command"><button id="send">Send</button></form></footer>
<script>
(()=>{const tabs=document.querySelector('#tabs'),out=document.querySelector('#transcript'),status=document.querySelector('#status'),interaction=document.querySelector('#interaction'),form=document.querySelector('#form'),input=document.querySelector('#input'),send=document.querySelector('#send'),scroll=document.querySelector('#scroll');let snapshot=null,active='',timer=0,closed=false;const cleared={};
const ansi16=['#000000','#800000','#008000','#808000','#000080','#800080','#008080','#c0c0c0','#808080','#ff0000','#00ff00','#ffff00','#0000ff','#ff00ff','#00ffff','#ffffff'];
function schedule(){clearTimeout(timer);timer=setTimeout(load,70)}
async function load(){if(closed)return;try{const r=await fetch('api/v1/snapshot',{cache:'no-store'});if(!r.ok)throw new Error(await r.text());snapshot=await r.json();render()}catch(e){status.innerHTML='<span class="notice">'+escapeHTML(String(e))+'</span>'}}
function escapeHTML(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ansi256(n){n=Math.max(0,Math.min(255,n));if(n<16)return ansi16[n];if(n<232){const v=n-16,c=x=>x?55+x*40:0;return '#'+[c(Math.floor(v/36)),c(Math.floor(v/6)%6),c(v%6)].map(x=>x.toString(16).padStart(2,'0')).join('')}return '#'+(8+(n-232)*10).toString(16).padStart(2,'0').repeat(3)}
function ansiHTML(value){let state={},text='',html='';const css=()=>[state.fg&&'color:'+state.fg,state.bg&&'background-color:'+state.bg,state.bold&&'font-weight:700',state.dim&&'opacity:.65',state.italic&&'font-style:italic',state.underline&&'text-decoration:underline',state.strike&&'text-decoration:line-through'].filter(Boolean).join(';');const flush=()=>{if(!text)return;const style=css(),safe=escapeHTML(text);html+=style?'<span style="'+style+'">'+safe+'</span>':safe;text=''};for(let i=0;i<value.length;){if(value[i]==='\x1b'&&value[i+1]==='['){const end=value.indexOf('m',i+2);if(end>=0){flush();const codes=value.slice(i+2,end).split(';').map(x=>x===''?0:Number(x)||0);for(let j=0;j<codes.length;j++){const c=codes[j];if(c===0)state={};else if(c===1)state.bold=true;else if(c===2)state.dim=true;else if(c===3)state.italic=true;else if(c===4)state.underline=true;else if(c===9)state.strike=true;else if(c===22){state.bold=false;state.dim=false}else if(c===23)state.italic=false;else if(c===24)state.underline=false;else if(c===29)state.strike=false;else if(c===39)delete state.fg;else if(c===49)delete state.bg;else if(c>=30&&c<=37)state.fg=ansi16[c-30];else if(c>=90&&c<=97)state.fg=ansi16[c-90+8];else if(c>=40&&c<=47)state.bg=ansi16[c-40];else if(c>=100&&c<=107)state.bg=ansi16[c-100+8];else if((c===38||c===48)&&codes[j+1]===5&&j+2<codes.length){state[c===38?'fg':'bg']=ansi256(codes[j+2]);j+=2}else if((c===38||c===48)&&codes[j+1]===2&&j+4<codes.length){state[c===38?'fg':'bg']='rgb('+codes[j+2]+','+codes[j+3]+','+codes[j+4]+')';j+=4}}i=end+1;continue}}text+=value[i++]};flush();return html}
function render(){const views=snapshot.presentation.views||[];if(!views.some(v=>v.id===active))active=snapshot.presentation.active||(views[0]&&views[0].id)||'';tabs.replaceChildren(...views.map(v=>{const b=document.createElement('button');b.className='tab '+(v.id===active?'active ':'')+(v.status==='running'?'running':'');b.textContent=v.name||v.id;b.onclick=()=>{active=v.id;render()};return b}));const v=views.find(v=>v.id===active);const nearBottom=scroll.scrollHeight-scroll.scrollTop-scroll.clientHeight<80;const lines=v?v.lines.slice(cleared[active]||0):[];out.innerHTML=lines.length?ansiHTML(lines.join('\n')):'No transcript yet.';out.className='transcript '+(lines.length?'':'empty');status.innerHTML=ansiHTML(snapshot.presentation.status_bar||'Connecting to qcode…');renderInteraction((snapshot.runtime.interactions||[]).find(x=>x.agent_id===active)||(snapshot.runtime.interactions||[])[0]);if(nearBottom)scroll.scrollTop=scroll.scrollHeight}
function choice(label,value,id){const b=document.createElement('button');b.textContent=label;b.onclick=()=>resolve(id,value);return b}
function renderInteraction(item){interaction.replaceChildren();interaction.className='interaction'+(item?' open':'');if(!item)return;let payload={};try{payload=typeof item.payload==='string'?JSON.parse(item.payload):item.payload||{}}catch(_){}const title=document.createElement('div');title.className='interaction-title';title.textContent=item.kind.replaceAll('_',' ');interaction.append(title);const choices=document.createElement('div');choices.className='choices';if(item.kind==='directory_approval'){title.textContent='Directory access: '+(payload.requested||'');choices.append(choice('Grant '+(payload.proposed||'requested path'),{selected:payload.proposed||payload.requested,approved:true},item.id),choice('Deny',{selected:'',approved:false},item.id))}else if(item.kind==='questions'){const questions=Array.isArray(payload)?payload:[];title.textContent=questions.map(q=>q.Text||q.text).join(' / ');const answer=()=>{const values=questions.map(q=>prompt(q.Text||q.text,(q.Options||q.options||[]).join(' / '))||'');resolve(item.id,values)};choices.append(choice('Answer questions',null,item.id));choices.lastChild.onclick=answer}else if(item.kind==='learning_approval'){title.textContent='Apply the proposed global learning changes?';choices.append(choice('Apply',true,item.id),choice('Reject',false,item.id))}else{choices.append(choice('Start implementation','implement',item.id),choice('Stay in plan mode','stay',item.id))}interaction.append(choices)}
async function resolve(id,value){try{const r=await fetch('api/v1/interactions/'+encodeURIComponent(id)+'/resolve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({value})});if(!r.ok)throw new Error(await r.text());schedule()}catch(e){status.innerHTML='<span class="notice">'+escapeHTML(String(e))+'</span>'}}
function downloadExport(){const views=(snapshot.presentation.views||[]);let body='<h1>qcode session</h1>';for(const v of views)body+='<h2>'+escapeHTML(v.name||v.id)+'</h2><pre>'+escapeHTML(v.lines.join('\n').replace(ansi,''))+'</pre>';const blob=new Blob(['<!doctype html><meta charset="utf-8"><title>qcode session</title><style>body{background:#07090d;color:#d8e0ea;font-family:monospace;padding:2rem}pre{white-space:pre-wrap}</style>'+body],{type:'text/html'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='qcode-session.html';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
form.onsubmit=async e=>{e.preventDefault();let line=input.value.trim();if(!line)return;if(line==='/exit'||line==='/quit'){closed=true;events.close();status.textContent='Disconnected';send.disabled=true;input.disabled=true;return}if(line==='/clear'){const v=(snapshot.presentation.views||[]).find(v=>v.id===active);cleared[active]=v?v.lines.length:0;input.value='';render();return}if(line.startsWith('/export')){downloadExport();input.value='';return}const match=line.match(/^\/agent switch\s+(\S+)$/);if(match){active=match[1];input.value='';render();return}const closing=line.match(/^\/agent close\s+(\S+)$/);if(closing){if(!confirm('Close '+closing[1]+'?'))return;line=line+' --yes'}if(line==='/model'){const v=prompt('Model and optional thinking level (model [thinking])');if(!v)return;line='/model '+v}if(line==='/tool'){const v=prompt('Tool change (name on|off)');if(!v)return;line='/tool '+v}if(line==='/skill'){const v=prompt('Comma-separated skill names, or none');if(v===null)return;line='/skill '+(v||'none')}if(line==='/resume'){const v=prompt('Saved session ID');if(!v)return;line='/resume '+v}if(line==='/agent'||line==='/agent new'){const v=prompt('Model for the new agent');if(!v)return;line='/agent new '+v}send.disabled=true;try{const r=await fetch('api/v1/actions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({line})});if(!r.ok)throw new Error(await r.text());input.value='';schedule()}catch(e){status.innerHTML='<span class="notice">'+escapeHTML(String(e))+'</span>'}finally{send.disabled=false;input.focus()}};
const events=new EventSource('api/v1/events');events.addEventListener('refresh',schedule);events.addEventListener('runtime',schedule);events.onerror=()=>{status.innerHTML='<span class="notice">Reconnecting…</span>'};load();input.focus()})();
</script></body></html>`
